### ISSUE TITLE
Broken blog link

### ISSUE THREAD

**Issue by shubhamagarwal92** [anyscale/factuality-eval#1]
Hi! 

It seems that the link for the blog is broken.
There is no page: https://www.anyscale.com/blog/can-you-trust-llama-2-and-chatgpt-to-factually-summarize
Is it the same as https://www.anyscale.com/blog/llama-2-is-about-as-factually-accurate-as-gpt-4-for-summaries-and-is-30x-cheaper or a different blog?

**Comment by waleedkadous** [comment]
Thank you for letting me know! Should be fixed now.
